### ISSUE TITLE
Favourite buttons being too large for main window

### ISSUE THREAD

**Issue by rmit-s3543824-jayden-joyce** [ToddRMIT/WeatherApp#30]
On the first start up, the favourite buttons will fit the window size but if you remove the buttons, close the window, reopen the window and favourite some stations, the favourite buttons will extend beyond the main window size. Although, closing and reopening the window will rectify this.

**Comment by ToddRMIT** [comment]
It seems that the width of the window is calculated on the button widths when the window is drawn. We probably need to decide on 1. Fixed button widths and 2. Fixed window width.
